const surpriseOptions = [
  "Give me 5 sentences in French for beginners.",
  "Give me one sentence using the word hope in German.",
  "Give me 10 sentences in Hebrew using the word שלום.",
  "Give me 5 sentences in Hebrew using the word שלום.",
  "Provide me with 3 phrases in Spanish for travelers.",
  "Give me a sentence using the word amor in Italian.",
  "Share 7 sentences in Russian with the word привет.",
  "Please, give me 4 sentences in Japanese for tourists.",
  "Could you give me 6 phrases in Chinese for basic conversations?",
  "I need a sentence in Korean using the word 안녕하세요.",
  "Give me 8 sentences in Arabic using the word مرحبا.",
  "Could you provide 5 sentences in Portuguese for beginners?",
  "Give me 6 sentences in German using the word Freude.",
  "Can you share 9 phrases in Spanish using the word gracias?",
  "I'd like 7 sentences in Italian with the word ciao.",
  "Provide me with 5 sentences in Russian using the word любовь.",
  "Please, give me 10 sentences in French using the word bonjour.",
  "Could you give me 8 sentences in Japanese using the word ありがとう?",
  "Give me 6 sentences in Korean with the word 사랑.",
  "I need 4 phrases in Arabic using the word شكرا.",
  "Provide me with 7 sentences in Chinese using the word 你好.",
  "Please, give me 5 sentences in Portuguese using the word olá.",
  "Could you share 6 phrases in German using the word Hallo?",
  "Give me 9 sentences in Spanish using the word amigo.",
  "I'd like 7 sentences in Italian with the word amico.",
  "Can you give me 5 sentences in Russian using the word друг?",
  "Please, provide me with 8 sentences in French using the word ami.",
  "Could you share 6 sentences in Japanese using the word 友達?",
  "Give me 10 sentences in Korean with the word 친구.",
  "Provide me with 3 phrases in Spanish for travelers.",
  "Give me a sentence using the word amor in Italian.",
  "Share 7 sentences in Russian with the word привет.",
  "Please, give me 4 sentences in Japanese for tourists.",
  "Could you give me 6 phrases in Chinese for basic conversations?",
  "I need a sentence in Korean using the word 안녕하세요.",
  "Give me 8 sentences in Arabic using the word مرحبا.",
  "Give me 5 sentences in Catalan with the word gràcies.",
  "Please, provide me with 3 sentences in Basque with the word eskerrik asko.",
  "Could you give me 7 sentences in Galician with the word grazas?",
  "I'd like 6 sentences in Welsh with the word diolch.",
  "Can you share 4 sentences in Irish with the word go raibh maith agat?",
  "Give me 6 sentences in Scottish Gaelic with the word tapadh leat.",
  "I need 9 sentences in Breton with the word trugarez.",
  "Provide me with 5 phrases in Luxembourgish with the word merci.",
  "Share 7 sentences in Maltese with the word grazzi.",
  "Could you give me 6 sentences in Manx with the word gura mie ayd?",
  "Please, give me 5 sentences in Occitan with the word gràcias.",
  "I'd like 7 sentences in Corsican with the word ghjè.",
  "Can you share 4 sentences in Sicilian with the word grazzi.",
  "Give me 6 sentences in Sardinian with the word gràtzias.",
  "I need 9 sentences in Friulian with the word gracie.",
  "Provide me with 5 phrases in Romansh with the word grazia.",
  "Share 7 sentences in Aragonese with the word gracias.",
  "Could you give me 6 sentences in Asturian with the word gracies?",
  "Please, give me 5 sentences in Ladin with the word gracies.",
  "I'd like 7 sentences in Venetian with the word graxie.",
  "Can you share 4 sentences in Piedmontese with the word gràssie.",
  "Give me 6 sentences in Lombard with the word gràssie.",
  "I need 9 sentences in Emilian-Romagnol with the word grasie.",
  "Provide me with 5 phrases in Neapolitan with the word grazie.",
  "Share 7 sentences in Ligurian with the word grazie.",
  "Could you give me 6 sentences in Romani with the word ačhala?",
  "Please, give me 5 sentences in Dalmatian with the word hvala.",
  "I'd like 7 sentences in Aromanian with the word mersi.",
  "Can you share 4 sentences in Yiddish with the word דאַנק.",
  "Give me 5 sentences in Quechua with the word sulpayki.",
  "Please, provide me with 3 sentences in Maori with the word mihi.",
  "Could you give me 7 sentences in Samoan with the word fa'amalie?",
  "I'd like 6 sentences in Hawaiian with the word mahalo.",
  "Can you share 4 sentences in Fijian with the word vinaka?",
  "Give me 6 sentences in Tongan with the word malo.",
  "I need 9 sentences in Tahitian with the word mauruuru.",
  "Provide me with 5 phrases in Rapa Nui with the word mauruuru.",
  "Share 7 sentences in Cook Islands Maori with the word meitaki.",
  "Could you give me 6 sentences in Marshallese with the word kommol tata?",
  "Please, give me 5 sentences in Palauan with the word siulang.",
  "I'd like 7 sentences in Chamorro with the word mahålang.",
  "Can you share 4 sentences in Gilbertese with the word ko rabwa.",
  "Give me 6 sentences in Rotuman with the word faiaksea.",
  "I need 9 sentences in Nauruan with the word reker.",
  "Provide me with 5 phrases in Tokelauan with the word fakafetai.",
  "Share 7 sentences in Tuvaluan with the word fakafetai.",
  "Could you give me 6 sentences in Niuean with the word fakaaue.",
  "Please, give me 5 sentences in Pitkern with the word tangkyu.",
  "I'd like 7 sentences in Tahitian Creole with the word mèsi.",
  "Can you share 4 sentences in Bislama with the word tangkiu.",
  "Give me 6 sentences in Solomon Islands Pijin with the word tangkyu.",
  "I need 9 sentences in Vanuatu Bislama with the word tangkiu.",
  "Provide me with 5 phrases in Papua New Guinean Tok Pisin with the word tenk yu.",
  "Share 7 sentences in Hiri Motu with the word tenkyu.",
  "Could you give me 6 sentences in Solomon Islands Motu with the word tangkiu.",
  "Please, give me 5 sentences in Torres Strait Creole with the word tankyu.",
  "I'd like 7 sentences in Australian Kriol with the word tank yu.",
  "Can you share 4 sentences in Darug with the word muru yu.",
  "Give me 5 sentences in Basque with the word eskerrik asko.",
  "Please, provide me with 3 sentences in Catalan with the word gràcies.",
  "Could you give me 7 sentences in Galician with the word grazas?",
  "I'd like 6 sentences in Welsh with the word diolch.",
  "Can you share 4 sentences in Irish with the word go raibh maith agat?",
  "Give me 6 sentences in Scottish Gaelic with the word tapadh leat.",
  "I need 9 sentences in Breton with the word trugarez.",
  "Provide me with 5 phrases in Luxembourgish with the word merci.",
  "Share 7 sentences in Maltese with the word grazzi.",
  "Could you give me 6 sentences in Manx with the word gura mie ayd?",
  "Please, give me 5 sentences in Occitan with the word gràcias.",
  "I'd like 7 sentences in Corsican with the word ghjè.",
  "Can you share 4 sentences in Sicilian with the word grazzi.",
  "Give me 6 sentences in Sardinian with the word gràtzias.",
  "I need 9 sentences in Friulian with the word gracie.",
  "Provide me with 5 phrases in Romansh with the word grazia.",
  "Share 7 sentences in Aragonese with the word gracias.",
  "Could you give me 6 sentences in Asturian with the word gracies?",
  "Please, give me 5 sentences in Ladin with the word gracies.",
  "I'd like 7 sentences in Venetian with the word graxie.",
  "Can you share 4 sentences in Piedmontese with the word gràssie.",
  "Give me 6 sentences in Lombard with the word gràssie.",
  "I need 9 sentences in Emilian-Romagnol with the word grasie.",
  "Provide me with 5 phrases in Neapolitan with the word grazie.",
  "Share 7 sentences in Ligurian with the word grazie.",
  "Could you give me 6 sentences in Romani with the word ačhala?",
  "Please, give me 5 sentences in Dalmatian with the word hvala.",
  "I'd like 7 sentences in Aromanian with the word mersi.",
  "Can you share 4 sentences in Yiddish with the word דאַנק.",
  "Give me 5 sentences in Quechua with the word sulpayki.",
  "Please, provide me with 3 sentences in Maori with the word mihi.",
  "Could you give me 7 sentences in Samoan with the word fa'amalie?",
  "I'd like 6 sentences in Hawaiian with the word mahalo.",
  "Can you share 4 sentences in Fijian with the word vinaka?",
  "Give me 6 sentences in Tongan with the word malo.",
  "I need 9 sentences in Tahitian with the word mauruuru.",
  "Provide me with 5 phrases in Rapa Nui with the word mauruuru.",
  "Share 7 sentences in Cook Islands Maori with the word meitaki.",
  "Could you give me 6 sentences in Marshallese with the word kommol tata?",
  "Please, give me 5 sentences in Palauan with the word siulang.",
  "I'd like 7 sentences in Chamorro with the word mahålang.",
  "Can you share 4 sentences in Gilbertese with the word ko rabwa.",
  "Give me 6 sentences in Rotuman with the word faiaksea.",
  "I need 9 sentences in Nauruan with the word reker.",
  "Provide me with 5 phrases in Tokelauan with the word fakafetai.",
  "Share 7 sentences in Tuvaluan with the word fakafetai.",
  "Could you give me 6 sentences in Niuean with the word fakaaue.",
  "Please, give me 5 sentences in Pitkern with the word tangkyu.",
  "I'd like 7 sentences in Tahitian Creole with the word mèsi.",
  "Can you share 4 sentences in Bislama with the word tangkiu.",
  "Give me 6 sentences in Solomon Islands Pijin with the word tangkyu.",
  "I need 9 sentences in Vanuatu Bislama with the word tangkiu.",
  "Provide me with 5 phrases in Papua New Guinean Tok Pisin with the word tenk yu.",
  "Share 7 sentences in Hiri Motu with the word tenkyu.",
  "Could you give me 6 sentences in Solomon Islands Motu with the word tangkiu.",
  "Please, give me 5 sentences in Torres Strait Creole with the word tankyu.",
  "I'd like 7 sentences in Australian Kriol with the word tank yu.",
  "Can you share 4 sentences in Darug with the word muru yu.",
  "Give me 5 sentences in Basque with the word eskerrik asko.",
  "Please, provide me with 3 sentences in Catalan with the word gràcies.",
  "Could you give me 7 sentences in Galician with the word grazas?",
  "I'd like 6 sentences in Welsh with the word diolch.",
  "Can you share 4 sentences in Irish with the word go raibh maith agat?",
  "Give me 6 sentences in Scottish Gaelic with the word tapadh leat.",
  "I need 9 sentences in Breton with the word trugarez.",
  "Provide me with 5 phrases in Luxembourgish with the word merci.",
  "Share 7 sentences in Maltese with the word grazzi.",
  "Could you give me 6 sentences in Manx with the word gura mie ayd?",
  "Please, give me 5 sentences in Occitan with the word gràcias.",
  "I'd like 7 sentences in Corsican with the word ghjè.",
  "Can you share 4 sentences in Sicilian with the word grazzi.",
  "Give me 6 sentences in Sardinian with the word gràtzias.",
  "I need 9 sentences in Friulian with the word gracie.",
  "Provide me with 5 phrases in Romansh with the word grazia.",
  "Share 7 sentences in Aragonese with the word gracias.",
  "Could you give me 6 sentences in Asturian with the word gracies?",
  "Please, give me 5 sentences in Ladin with the word gracies.",
  "I'd like 7 sentences in Venetian with the word graxie.",
  "Can you share 4 sentences in Piedmontese with the word gràssie.",
  "Give me 6 sentences in Lombard with the word gràssie.",
  "I need 9 sentences in Emilian-Romagnol with the word grasie.",
  "Provide me with 5 phrases in Neapolitan with the word grazie.",
  "Share 7 sentences in Ligurian with the word grazie.",
  "Could you give me 6 sentences in Romani with the word ačhala?",
  "Please, give me 5 sentences in Dalmatian with the word hvala.",
  "I'd like 7 sentences in Aromanian with the word mersi.",
  "Can you share 4 sentences in Yiddish with the word דאַנק.",
  "Give me 5 sentences in Quechua with the word sulpayki.",
  "Please, provide me with 3 sentences in Maori with the word mihi.",
  "Could you give me 7 sentences in Samoan with the word fa'amalie?",
  "I'd like 6 sentences in Hawaiian with the word mahalo.",
  "Can you share 4 sentences in Fijian with the word vinaka?",
  "Give me 6 sentences in Tongan with the word malo.",
  "I need 9 sentences in Tahitian with the word mauruuru.",
  "Provide me with 5 phrases in Rapa Nui with the word mauruuru.",
  "Share 7 sentences in Cook Islands Maori with the word meitaki.",
  "Could you give me 6 sentences in Marshallese with the word kommol tata?",
  "Please, give me 5 sentences in Palauan with the word siulang.",
  "I'd like 7 sentences in Chamorro with the word mahålang.",
  "Can you share 4 sentences in Gilbertese with the word ko rabwa.",
  "Give me 6 sentences in Rotuman with the word faiaksea.",
  "I need 9 sentences in Nauruan with the word reker.",
  "Provide me with 5 phrases in Tokelauan with the word fakafetai.",
  "Share 7 sentences in Tuvaluan with the word fakafetai.",
  "Could you give me 6 sentences in Niuean with the word fakaaue.",
  "Please, give me 5 sentences in Pitkern with the word tangkyu.",
  "I'd like 7 sentences in Tahitian Creole with the word mèsi.",
  "Can you share 4 sentences in Bislama with the word tangkiu.",
  "Give me 6 sentences in Solomon Islands Pijin with the word tangkyu.",
  "I need 9 sentences in Vanuatu Bislama with the word tangkiu.",
  "Provide me with 5 phrases in Papua New Guinean Tok Pisin with the word tenk yu.",
  "Share 7 sentences in Hiri Motu with the word tenkyu.",
  "Could you give me 6 sentences in Solomon Islands Motu with the word tangkiu.",
  "Please, give me 5 sentences in Torres Strait Creole with the word tankyu.",
  "I'd like 7 sentences in Australian Kriol with the word tank yu.",
  "Can you share 4 sentences in Darug with the word muru yu.",
  
];
export default surpriseOptions;
